# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0766d9a15c0509403dcbd1eae3766bbaee9b365b583d94bba527a66a752c4c94efce73fddb9a1f589fa97aecccffdb2fd3d72058b1ec03c4e696206c7763f2f4

test:
  secret_key_base: 68087ce228390794d3595f03d42939a5de1123bda45f9fa10266ee2b33146d31fb35603f96eb8c9e79e9ae53af359a09c8fcaa20b9cc696d9a8491261f253c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
